import React from 'react'
import Navbar from './Navbar'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Layout = ({children}) => {
  return (
    <div>
      <Head>
        <title>getStaticProps & getServerSideRendering</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <Navbar />
      </header>

      <main className={'py-5 h-screen'}>
        {children}
      </main>
    </div>
  )
}

export default Layout